### ISSUE TITLE
Sugerencia durante el reinicio de Trivia

### ISSUE THREAD

**Issue by OswaldoAD** [9-natalia/Trivia#1]
Como sugerencia al momento de reiniciar la Trivia ya no debería pedir de nuevo el nombre , si no empezar de nuevo con las preguntas

**Comment by 9-natalia** [comment]
Ok, gracias por tu sugerencia. Lo revisaré.

**Comment by OswaldoAD** [comment]
Mi discord por siaca WaldoAD#1679
