### ISSUE TITLE
Error de Concatenación 

### ISSUE THREAD

**Issue by OswaldoAD** [9-natalia/Trivia#2]
## Problema:
En la pregunta 3 de la Trivia al colocar la opción "a" nos lanza un mensaje de error en la consola después de evaluar que es incorrecta

## Resultado de la consola:
'''
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    print("\n"+punto,"puntos")
TypeError: can only concatenate str (not "int") to str
'''
![image](https://user-images.githubusercontent.com/113272281/190838089-c8d3dede-4cda-408b-af0f-0e53b91892c9.png)

## Posible solución:
No se puede concatenar un string con un integer el código en la línea 125 debería ser como sigue
`print("\n",punto,"puntos")`

**Comment by 9-natalia** [comment]
Gracias, ya lo estoy revisando en estos momentos.
