### ISSUE TITLE
Error en el calculo de puntuación

### ISSUE THREAD

**Issue by OswaldoAD** [9-natalia/Trivia#3]
## Problema:
En la pregunta 3 al elegir la opción "c" me advierte que me restara unos puntos, sin embargo en la puntuación actual da un valor erróneo y no refleja el resultado de la resta. 

![image](https://user-images.githubusercontent.com/113272281/190838895-ddf96b26-d038-4ee2-8de9-a67c2e128dc3.png)

## Posible solución:
Al revisar el código tenemos dos posibles soluciones.
![image](https://user-images.githubusercontent.com/113272281/190839031-cd171863-b25a-4814-a52f-dafec82eff95.png)
La primera es cambiar la línea 128 por:
`puntaje-= punto`
o cambiar la línea 130 por:
`print("\nPerdistes 5 puntos")`

**Comment by 9-natalia** [comment]
@OswaldoAD  gracias por la observación. Lo revisaré
